module.exports = require('reflux').createActions({
  'listWaitClearCreditCard': {children: ['done','error']},
  'exportWaitClearCreditCard': {children:['done', 'error']},
  'listWaitAssign': {children: ['done', 'error']},
  'exportWaitAssign': {children:['done', 'error']},
  'listInprocess': {children:['done', 'error']},
  'exportInprocess': {children:['done', 'error']},
  'listInTransit': {children:['done', 'error']},
  'exportInTransit': {children:['done', 'error']},
  'listArrived': {children:['done', 'error']},
  'exportArrived': {children:['done', 'error']},
  'listDelivered': {children:['done', 'error']},
  'exportDelivered': {children:['done', 'error']},
  'listException': {children:['done', 'error']},
  'exportException': {children:['done', 'error']},
  'listCancel': {children:['done', 'error']},
  'exportCancel': {children:['done', 'error']},
  'cancelBooking': {children:['done', 'error']},
  'changeStatusBooking': {children:['done', 'error']},
  'getDialogData': {children:['done', 'error']},
  'saveAddition': {children:['done','error']},
  'sentDocToEmail': {children:['done','error']},
  'getDialogDetailList': {children:['done','error']},
  'getDialogItemList': {children:['done','error']}
});
