module.exports = require('reflux').createActions({
  'list': {children:['done', 'error']},
  'export': {children:['done', 'error']},
  'getById': {children:['done', 'error']},
  'saveNew': {children:['done', 'error']},
  'delete': {children:['done', 'error']},
  'getSellInfo': {children:['done','error']},
  'getBarcode': {children:['done', 'error']},
  'save': {children:['done', 'error']},
  'listClose': {children:['done', 'error']},
  'exportClose': {children:['done', 'error']},
  'getCloseReturn': {children:['done', 'error']},
  'getListCollection': {children:['done', 'error']},
  'saveCollection': {children:['done', 'error']},
  'getMobileNumber': {children:['done', 'error']},
  'exportDunning': {children:['done', 'error']},
  'printCollectionReport': {children:['done', 'error']},
  'listClosediscount': {children:['done', 'error']},
  'exportClosediscount': {children:['done', 'error']},
  'saveClosediscount': {children:['done', 'error']},
  'closeCaStaffList': {children:['done', 'error']},
  'saveCloseCa': {children:['done', 'error']},
  'getContractID': {children:['done', 'error']},
  'getPersonCard': {children:['done', 'error']}
});
